### ISSUE TITLE
Can't connect to Lnd using gRPC

### ISSUE THREAD

**Issue by RastaAlex** [alexbosworth/ln-service#151]
Hi, I am new to using Lnd and I have problem with connecting to Lnd by using gRPC. 

a version of lnd: 0.14.2-beta
launch station: Docker 

When I try to connect lnd i received this problem:
```
503,FailedToConnectToDaemon
```

I linked two containers and can ping them with each other. Default ports are exposed as 8003: 10009, 8004:9735
I can work directly from lncli and everything works well but i can't connect from outside in any way

index.js
```js
import lnService from 'ln-service'

const { lnd } = lnService.authenticatedLndGrpc({
cert: 'base64 -w0 ~/.lnd/tls.cert'
macaroon: 'base64 -w0 ~/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'
socket: 'lnd:10009'
)}

const nodePublicKey = (await lnService.getWalletInfo({ lnd })).public_key
console.log(nodePublicKey )
```
start-lnd.sh
```sh
exec lnd \
    --noseedbackup \
    "--$CHAIN.active" \
    "--$CHAIN.$NETWORK" \
    "--$CHAIN.node"="$BACKEND" \
    "--$BACKEND.rpccert"="/rpc/rpc.cert" \
    "--$BACKEND.rpchost"="blockchain" \
    "--$BACKEND.rpcuser"="$RPCUSER" \
    "--$BACKEND.rpcpass"="$RPCPASS" \
    "--rpclisten=0.0.0.0:10009" \
    "--tlsextraip=0.0.0.0" \
    --debuglevel="$DEBUG" \
    "$@"
```
docker-compose.yml
```yml
lnd:
    image: lnd
    container_name: lnd
    networks:
      - bridge
    ports:
      - 8004:9735
      - 8003:10009
    volumes:
      - shared:/rpc
      - lnd:/root/.lnd
    build:
      context: docker/lnd/
      dockerfile: lnd.Dockerfile
    environment:
      RPCUSER: $BTCD_RPC_USER
      RPCPASS: $BTCD_RPC_PASSWORD
      NETWORK: $BITCOIN_NETWORK
    entrypoint: ["./start-lnd.sh"]
    links:
      - "btcd:blockchain"
```
